apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvs-standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
      requests:
        storage: 100Gi
  storageClassName: cvs-standard
